export const queryKeys = {
  dashboard: ['dashboard'] as const,
  home: ['home'] as const,
  netWorth: ['net-worth'] as const,
  transactions: (filters?: Record<string, unknown>) =>
    ['transactions', filters ?? {}] as const,
  receipts: ['receipts'] as const,
  analytics: (period?: string) => ['analytics', period ?? 'month'] as const,
  goals: ['goals'] as const,
  warranties: ['warranties'] as const,
  inventory: ['inventory'] as const,
  profile: ['profile'] as const,
  preferences: ['preferences'] as const,
  onboardingAnswers: ['onboarding-answers'] as const,
  onboardingStatus: (userId: string) => ['onboarding-status', userId] as const,
  financialProfile: ['financial-profile'] as const,
  assets: ['assets'] as const,
  liabilities: (userId: string) => ['liabilities', userId] as const,
  prices: ['prices'] as const,
  emailEvents: (userId: string) => ['email-events', userId] as const,
  merchantGroups: (userId: string) => ['merchant-groups', userId] as const,
} as const;
