/**
 * Fixture mínima válida de FinancialState — apenas para testes Node.
 */
import type { FinancialState } from './financial-state.types';

const EMPTY_BUDGET: FinancialState['budget'] = {
  available: 0,
  dailySafeSpend: 0,
  daysRemaining: 1,
  monthEndProjection: 0,
  consumptionSpending: 0,
  components: {
    budgetAccountBalance: 0,
    incomeReceived: 0,
    registeredExpenses: 0,
    creditCardPayments: 0,
    creditCardPurchases: 0,
    goalReserved: 0,
    futureObligations: 0,
    loanPaymentsPaid: 0,
    loanAmortizationsPaid: 0,
    financialCharges: 0,
    movedOutOfBudget: 0,
    movedIntoBudget: 0,
  },
  budgetAccountsIncluded: [],
  budgetAccountsExcluded: [],
  obligations: [],
  warnings: [],
  notes: [],
};

export function createTestFinancialState(
  overrides: Partial<FinancialState> = {},
): FinancialState {
  const asOf = overrides.asOf ?? new Date('2026-07-15T12:00:00');
  return {
    asOf,
    accounts: [],
    creditCards: [],
    credits: [],
    budget: EMPTY_BUDGET,
    availableThisMonth: 0,
    dailySafeSpend: 0,
    budgetExplanation: { title: 'Orçamento', result: 0, lines: [], formula: '' },
    cashFlow: {
      monthlyIncome: 0,
      monthlyExpenses: 0,
      net: 0,
      savingsRate: 0,
      weeklySpending: 0,
    },
    netWorth: {
      netWorth: 0,
      totalAssets: 0,
      totalLiabilities: 0,
      breakdown: { accounts: 0, inventory: 0, investments: 0, savings: 0, liabilities: 0 },
      assetsByCategory: [],
    },
    netWorthExplanation: { title: 'Património', result: 0, lines: [], formula: '' },
    projection: { netWorth: 0, futureMovementsDelta: 0 },
    previousMonthNetWorth: 0,
    netWorthChangePercent: 0,
    netWorthChangeThisMonth: 0,
    goalProgress: [],
    subscriptions: { items: [], monthlyTotal: 0, renewingSoon: 0 },
    investmentSummary: { totalBalance: 0, accountCount: 0 },
    creditSummary: { totalDebt: 0, monthlyPayments: 0, cardCount: 0, loanCount: 0 },
    calendar: [],
    metrics: {
      savingsRate: 0,
      debtRatio: 0,
      emergencyMonths: 0,
      recurringRatio: 0,
      budgetAccuracy: 0,
      averageDailySpend: 0,
      incomeStability: 0,
      expenseConcentration: 0,
      subscriptionLoad: 0,
      financialRunway: 0,
      netWorthGrowth: 0,
      goalVelocity: 0,
      financialFreedomScore: 0,
    },
    insights: [],
    warnings: [],
    suggestions: [],
    financialSuggestions: [],
    attentionItems: [],
    healthScore: {
      score: 0,
      band: 'critical',
      bandLabel: 'Crítico',
      breakdown: { savings: 0, debt: 0, subscriptions: 0, goals: 0, stability: 0 },
      summary: '',
      input: {
        netWorth: 0,
        netWorthChangePercent: 0,
        monthlyIncome: 0,
        monthlyExpenses: 0,
        monthlySubscriptionCost: 0,
        totalDebt: 0,
        goals: [],
        subscriptionsRenewingSoon: 0,
      },
      explanation: { earned: [], missing: [] },
    },
    events: { total: 0, byType: {} },
    dashboard: { personalInflation: null },
    ...overrides,
  };
}
